version: "3.8"

services:
  db:
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - BankAccountNetwork
volumes:
  postgres_data:
    driver: local

networks:
  BankAccountNetwork:
    external: true